social_media/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings
from social_media_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('signup/', views.usersignup, name='usersignup'),
    path('signin/', views.usersignin, name='usersignin'),
    path('feed/', views.usersfeed, name='usersfeed'),
    path('status/<int:UserStatus_pk>', views.status_save, name='status_save'),
    path('like/', views.like_post, name='like_post'),
    path('search-users/', views.usersearch, name='usersearch'),
    path('search/', views.search, name='search'),
    path('logout/', views.logoutuser, name='userslogout'),
    path('savepost/', views.savepost, name='userpost'),
    path('comment/<int:pk>', views.commentpost, name='commentpost'),
    path('deletecomment/<int:comment_pk>/', views.deletecomment, name='usercommentdelete'),
    path('<int:post_pk>/deletepost/', views.deletepost, name='userpostdelete'),
    path('profile/<int:user_id>', views.userprofile, name='userprofile'),
    path('saveprofile/<int:profile_pk>', views.saveprofile, name='usersaveprofile'),
    path('settings/', views.editprofile, name='editprofile'),
    path('setprofile/', views.setprofile, name='setprofile'),
    path('savenewprofile/', views.savenewprofile, name='savenewprofile'),
    path('add-friend/<int:id>/',views.send_request,name='add-friend'),
    path('cancel-request/<int:id>/',views.cancel_request,name='cancel-request'),
    path('accept/<int:id>/',views.accept_request,name='accept'),
    path('ignore-request/<int:id>/',views.ignore_request,name='ignore-request'),
    path('remove-friend/<int:id>/',views.remove_friend,name='remove-friend'),
    path('room/<str:room_name>/', views.room, name='room'),
    path('blogs/', views.blog, name='blog'),
    path('blog_detail/<int:pk>', views.blog_detail, name='blog_detail'),
    path('write-blog/', views.writeblog, name='writeblog'),
    path('blogs-create/', views.saveblog, name='saveblog'),
    path('my-blogs/', views.myBlogs, name='myBlogs'),
    path('edit-blog/<int:pk>', views.EditBlogs, name='blogedit'),
    path('update-blog/<int:pk>', views.updateblog, name='updateblog'),
    path('delete-blog/<int:pk>', views.deleteblog, name='deleteblog'),
    path('searchblog', views.blogsearch, name='searchblog'),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

social_media_app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.base import Model
from django.db.models.signals import post_save

# Create your models here.

class post(models.Model):
    user = models.ForeignKey(User,default='' , related_name='has_liked', on_delete=models.CASCADE)
    caption = models.CharField(max_length=100)
    image = models.FileField(upload_to='images/', null=True, blank=True)
    video = models.FileField(upload_to='videos/', null=True, blank=True)
    created = models.DateTimeField(auto_now_add=True)
    like = models.ManyToManyField(User, null=True, blank=True, default=0)

    def __str__(self):
        return self.caption

    def total_likes(self):
        return self.like.count()

class profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='profile')
    desc = models.TextField(null=True)
    pfp = models.ImageField(default='profile.png', upload_to='profile_pics/', null=True, blank=True)
    cover = models.ImageField(default='cover.png', upload_to='cover_pics/', null=True, blank=True)
    occupation = models.CharField(max_length=250, default='')
    friend = models.ManyToManyField(User, blank=True, null=True, related_name='friended')

    def __str__(self):
        return self.user.username

    def create_profile(sender,instance,created,**kwargs):
        if created:
            profile.objects.create(user=instance)

    post_save.connect(create_profile, sender=User)

class UserStatus(models.Model):
    status = models.CharField(max_length=50, default='Available', null=True, blank=True, editable=True)
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name='status')

    def __str__(self):
        return self.user.username

    def create_status(sender,instance,created,**kwargs):
        if created:
            UserStatus.objects.create(user=instance)

    post_save.connect(create_status, sender=User)

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    comment = models.CharField(max_length=250, null=True)
    post = models.ForeignKey(post, related_name='Comment', on_delete=models.CASCADE, blank=True, null=True)

    def __str__(self):
        return self.comment

class FriendRequest(models.Model):
	to_user = models.ForeignKey(User, related_name='to_user', on_delete=models.CASCADE)
	from_user = models.ForeignKey(User, related_name='from_user', on_delete=models.CASCADE)
	timestamp = models.DateTimeField(auto_now_add=True) # set when created

	def __str__(self):
		return "From {}, to {}".format(self.from_user.username, self.to_user.username)

class blog_Categorie(models.Model):
    categoryTitle = models.CharField(max_length=100)

    def __str__(self):
        return self.categoryTitle

class Blog(models.Model):
    blogTitle = models.CharField(max_length=100)
    blogContent = models.TextField()
    blogUser = models.ForeignKey(User, on_delete=models.CASCADE, default='')
    blogCreated = models.DateField(null=True, blank=True,auto_now_add=True)
    blogImgOne = models.ImageField(upload_to='Blogimages/', default='')
    blogCategory = models.ForeignKey(blog_Categorie, on_delete=models.CASCADE, default='')

    def __str__(self):
        return str(str(self.blogTitle)  + ' - ' + str(self.blogUser))

social_media_app/forms.py
from django import forms
from django.contrib.auth import models
from django.contrib.auth.models import User
from .models import Blog, post, profile, Comment, UserStatus

class PostForm(forms.ModelForm):
    class Meta:
        model = post
        fields = ['caption','image','video']

class UserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['username','email','first_name','last_name']

class ProfileForm(forms.ModelForm):
    class Meta:
        model = profile
        fields = ['desc','pfp','cover','occupation']

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['comment']

class StatusForm(forms.ModelForm):
    class Meta:
        model = UserStatus
        fields = ['status']

class BlogForm(forms.ModelForm):
    class Meta:
        model = Blog
        fields = ['blogTitle','blogContent','blogCategory','blogImgOne']

social_media_app/views.py
from django.http import response
from django.http.response import HttpResponse
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.models import User
from django.contrib.auth import login, logout, authenticate
from django.db import IntegrityError
from django.contrib.auth.decorators import login_required
from .models import post, profile, Comment, UserStatus, FriendRequest, Blog, blog_Categorie
from .forms import BlogForm, PostForm, ProfileForm, UserForm, CommentForm, StatusForm
from django.db.models import Q
from django.http import JsonResponse
from django.core import serializers

# Create your views here.

def home(request):
    return render(request, 'social_media/home.html')

def usersignup(request):
    if request.method == 'GET':
        return render(request, 'social_media/usersignup.html')
    else:
        email = request.POST['email']
        if User.objects.filter(email=email).exists():
            return render(request, 'social_media/usersignup.html', {'error':'Email already exists'})
        else:
            try:
                user = User.objects.create_user(username=request.POST['username'], password=request.POST['password'], email=request.POST['email'])
                user.save()
                login(request, user)
                return redirect('setprofile')
            except IntegrityError:
                return render(request, 'social_media/usersignup.html', {'error':'User already exists'})

def usersignin(request):
    if request.method == 'GET':
        return render(request, 'social_media/usersignin.html')
    else:
        user = authenticate(request, username=request.POST['username'], password=request.POST['password'])
        if user is None:
            return render(request, 'social_media/usersignin.html', {'errorsignin':'Invalid User/Password'})
        else:
            login(request, user)
            return redirect('usersfeed')

@login_required
def usersfeed(request):
    users = User.objects.all()
    posts = post.objects.filter(Q(user__in=request.user.profile.friend.all()) | Q(user=request.user)).order_by('-created')
    comments = Comment.objects.all()
    status_form = StatusForm(request.POST)
    friend_requests = FriendRequest.objects.filter(to_user=request.user)
    friends = request.user.profile.friend.all()
    Hasliked = []
    Hasnotliked = []
    empty = []
    Notempty = []
    for i in posts:
        likes = i.like.all()
        for like in likes:
            if i.like.filter(id=request.user.id).exists():
                Hasliked.append(i.id)
            else:
                Hasnotliked.append(i.id)
        if Hasliked == []:
            empty.append(i.id)
        else: 
            Notempty.append(i.id)
    context = {
        'Post':posts,
        'User':users,
        'form':PostForm(),
        'Profile':profile,
        'Form':CommentForm(),
        'Comment':comments,
        'Status':status_form,
        'fr':friend_requests,
        'friend':friends,
        'Hasliked':Hasliked,
        'Hasnotliked':Hasnotliked,
        'empty':empty,
        'Notempty':Notempty,
    }
    return render(request, 'social_media/feed.html', context=context)

@login_required
def status_save(request,UserStatus_pk):
    if request.method == 'POST':
        y=get_object_or_404(UserStatus, pk=UserStatus_pk)
        status = StatusForm(request.POST, instance=y)
        if status.is_valid():
            Status=status.save(commit=False)
            Status.user=request.user
            Status.save()
        return redirect(request.META['HTTP_REFERER']) #Returns me to the same page/back to that page

@login_required
def like_post(request):
    Post = get_object_or_404(post, id=request.GET.get('post_id'))
    cssClass = 'colorRed'
    if Post.like.filter(id=request.user.id).exists():
        Post.like.remove(request.user)
    else:
        Post.like.add(request.user)
    count = Post.like.count()
    users = Post.like.all() 
    user = []
    for i in users:
        user.append((i.username))
    response = {
        'count':count,
        'users':user,
        'cssClass':cssClass,
    }
    return JsonResponse(response)

@login_required
def usersearch(request):
    qur = request.GET.get('search')
    u = User.objects.filter(username__contains = qur)
    user = User.objects.all()
    friend = request.user.profile.friend.all()
    if u:
        return render(request, 'social_media/search.html', {'User':user,'User_search':u,'Profile':profile,'friend':friend})
    else:
        return render(request, 'social_media/search.html', {'User':user,'Error':'No users found! :(','friend':friend})

@login_required
def search(request):
    if 'term' in request.GET:
        qs = User.objects.filter(username__contains=request.GET.get('term'))
        users = list()
        for i in qs:
            users.append(i.username)
        return JsonResponse(users, safe=False)

@login_required
def logoutuser(request):
    if request.method == 'POST':
        logout(request)
        return redirect('usersignin')

@login_required
def savepost(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            Form = form.save(commit=False)
            Form.user = request.user
            Form.save()
            return redirect('usersfeed')

@login_required
def commentpost(request, pk):
    Post = get_object_or_404(post, pk=pk)
    comment = request.POST.get('comment')
    if request.method == 'POST':
        form = CommentForm(request.POST)
        if form.is_valid():
            Form = form.save(commit=False)
            Form.post = Post
            Form.comment = comment
            Form.user = request.user
            Form.save()
            return redirect('usersfeed') #Returns me to the same page/back to that page

@login_required
def deletecomment(request, comment_pk):
    comment = get_object_or_404(Comment, pk=comment_pk)
    if request.user == comment.user or comment.post.user.username:
        if request.method == 'GET':
            comment.delete()
            return redirect(request.META['HTTP_REFERER']) #Returns me to the same page/back to that page

@login_required
def deletepost(request, post_pk):
    Post = get_object_or_404(post, pk=post_pk, user=request.user)
    if request.method == 'GET':
        Post.delete()
        return redirect(request.META['HTTP_REFERER']) #Returns me to the same page/back to that page

@login_required
def userprofile(request, user_id=None):
    u=User.objects.all()
    user = get_object_or_404(User, id=user_id)
    sent_request = FriendRequest.objects.filter(from_user=request.user, to_user=user)
    if request.user.friended.filter(user=user):
        button_status = True
    else:
        button_status = False
    friends = user.friended.all()
    friend = request.user.profile.friend.all()
    if user:
        user = User.objects.get(id=user_id)
        Post = post.objects.order_by('-created')
    Hasliked = []
    Hasnotliked = []
    empty = []
    Notempty = []
    for i in Post:
        likes = i.like.all()
        for like in likes:
            if i.like.filter(id=request.user.id).exists():
                Hasliked.append(i.id)
            else:
                Hasnotliked.append(i.id)
        if Hasliked == []:
            empty.append(i.id)
        else: 
            Notempty.append(i.id)
    context = {
        'Post':Post,
        'User':user,
        'u':u,
        'button_status':button_status,
        'sent_request':sent_request,
        'friends':friends,
        'friend':friend,
        'Hasliked':Hasliked,
        'Hasnotliked':Hasnotliked,
        'empty':empty,
        'Notempty':Notempty,
    }
    return render(request,'social_media/profile.html', context=context)

@login_required
def saveprofile(request,profile_pk):
    if request.method == 'POST':
        y = get_object_or_404(profile, pk=profile_pk, user=request.user)
        form = ProfileForm(request.POST, request.FILES, instance=y)
        form2 = UserForm(request.POST, instance=request.user)
        if form.is_valid():
            Form = form.save(commit=False)
            Form.user = request.user
            Form.save()
        if form2.is_valid():
            form2.save()
        return redirect(request.META['HTTP_REFERER']) 

@login_required
def editprofile(request):
    form = ProfileForm(instance=request.user.profile)
    form2 = UserForm(instance=request.user)
    return render(request, 'social_media/settings.html', {'Form':form,'Form2':form2})

@login_required
def savenewprofile(request):
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES, instance=request.user.profile)
        form2 = UserForm(request.POST, instance=request.user)
        if form.is_valid():
            Form = form.save(commit=False)
            Form.user = request.user
            Form.save()
        if form2.is_valid():
            form2.save()
        return redirect('usersfeed')

@login_required
def setprofile(request):
    form = ProfileForm(request.POST,request.FILES)
    form2 = UserForm(request.POST)
    return render(request, 'social_media/setprofile.html', {'Form':form,'Form2':form2})

@login_required
def send_request(request,id):
    from_user=request.user
    to_user=User.objects.get(id=id)
    freq=FriendRequest.objects.get_or_create(from_user=from_user,to_user=to_user)
    return redirect(request.META['HTTP_REFERER']) #Returns me to the same page/back to that page

@login_required
def cancel_request(request,id):
    user1=request.user
    user2=User.objects.get(id=id)
    freq = FriendRequest.objects.filter(from_user=user1,to_user=user2)
    freq.delete()
    return redirect(request.META['HTTP_REFERER']) #Returns me to the same page/back to that page

@login_required
def accept_request(request,id):
    freq=FriendRequest.objects.get(id=id)
    user1=request.user
    user2=freq.from_user
    user1.profile.friend.add(user2)
    user2.profile.friend.add(user1)

social_media_app/templates/social_media/blog_create.html
{% extends 'social_media/base.html' %}

{% block content %}

{% load static %}

<style>
.center {
  position: absolute;
  display: inline-block;
  top: 50%; left: 50%;
  transform: translate(-50%, -50%);
}

/** Custom Select **/
.custom-select-wrapper {
  position: relative;
  display: inline-block;
  user-select: none;
}
  .custom-select-wrapper select {
    display: none;
  }
  .custom-select {
    position: relative;
    display: inline-block;
  }
    .custom-select-trigger {
      position: relative;
      display: block;
      width: 130px;
      padding: 0 84px 0 22px;
      font-size: 22px;
      font-weight: 300;
      color: #fff;
      line-height: 60px;
      background: #5c9cd8;
      border-radius: 4px;
      cursor: pointer;
    }
      .custom-select-trigger:after {
        position: absolute;
        display: block;
        content: '';
        width: 10px; height: 10px;
        top: 50%; right: 25px;
        margin-top: -3px;
        border-bottom: 1px solid #fff;
        border-right: 1px solid #fff;
        transform: rotate(45deg) translateY(-50%);
        transition: all .4s ease-in-out;
        transform-origin: 50% 0;
      }
      .custom-select.opened .custom-select-trigger:after {
        margin-top: 3px;
        transform: rotate(-135deg) translateY(-50%);
      }
  .custom-options {
    position: absolute;
    display: block;
    top: 100%; left: 0; right: 0;
    min-width: 100%;
    margin: 15px 0;
    border: 1px solid #b5b5b5;
    border-radius: 4px;
    box-sizing: border-box;
    box-shadow: 0 2px 1px rgba(0,0,0,.07);
    background: #fff;
    transition: all .4s ease-in-out;
    
    opacity: 0;
    visibility: hidden;
    pointer-events: none;
    transform: translateY(-15px);
  }
  .custom-select.opened .custom-options {
    opacity: 1;
    visibility: visible;
    pointer-events: all;
    transform: translateY(0);
  }
    .custom-options:before {
      position: absolute;
      display: block;
      content: '';
      bottom: 100%; right: 25px;
      width: 7px; height: 7px;
      margin-bottom: -4px;
      border-top: 1px solid #b5b5b5;
      border-left: 1px solid #b5b5b5;
      background: #fff;
      transform: rotate(45deg);
      transition: all .4s ease-in-out;
    }
    .option-hover:before {
      background: #f9f9f9;
    }
    .custom-option {
      position: relative;
      display: block;
      padding: 0 22px;
      border-bottom: 1px solid #b5b5b5;
      font-size: 18px;
      font-weight: 600;
      color: #b5b5b5;
      line-height: 47px;
      cursor: pointer;
      transition: all .4s ease-in-out;
    }
    .custom-option:first-of-type {
      border-radius: 4px 4px 0 0;
    }
    .custom-option:last-of-type {
      border-bottom: 0;
      border-radius: 0 0 4px 4px;
    }
    .custom-option:hover,
    .custom-option.selection {
      background: #f9f9f9;
    }
</style>

<div class="profile_new-user">
    <section class="feed_profile_show drop_shadow">
        <div class="feed_profile_media">
            <img src="{{ user.profile.pfp.url }}" class="feed_userpfp">
            <br>
            <img src="{{ user.profile.cover.url }}" class="feed_usercover">
        </div>
        <div class="feed_user_details">
            <div>Welcome <span style="font-weight: 900;">{{ user.first_name }} {{ user.last_name }}</span></div>
            <div>
                About {{ user.first_name }}:
                <br>
                {{ user.profile.desc|truncatechars:40 }}
            </div>
            <div class="UserStatus">
                <form action="{% url 'status_save' user.status.id %}" method="post" autocomplete="off">
                    {% csrf_token %}
                    <!-- {{ Status }} -->
                    <label for="status">Status:</label>
                    <input type="text" value="{{ user.status.status }}" name="status" maxlength="300"
                        id="id_status">
                    <button type="submit" name="UserStatus_pk">Update!</button>
                </form>
            </div>
        </div>
    </section>

    <section class="new_users drop_shadow">
        <div class="recenty_joined">Recently Joined:</div>
        {% for i in User reversed %}
        <div class="new_user_details_feed">
            <a href="{% url 'userprofile' user_id=i.id %}">
                <img src="{{ i.profile.pfp.url }}" class="new_user_pfp_feed" alt="">
                <div class="new_user_name_feed">
                    {{ i.first_name }} {{ i.last_name }}
                </div>
            </a>
        </div>
        {% endfor %}
    </section>
</div>

    <div class="main_class">
    <section class="feed">
        <div class="sub-feed drop_shadow" style="padding: 10px">
            <form autocomplete="off" action="{% url 'saveblog' %}" method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                <img src="{% static 'social_media/images/user-bg.jpg' %}" style="border-radius: 10px;">
                <div class="" style="font-size: 15px;">
                    <h1 class="text-center" style="color: rgb(145,145,145);">{{ error }}</h1>
                    <div class="ImgCategoryBlog">
                        <div>
                            <input type="file" accept="image/*" name="blogImgOne" id="id_blogImgOne" class="inputfile">
                            <label class="blogLabel blogPhotoLabel" for="id_blogImgOne" style="margin: 0;">Add Photo</label>
                        </div>
                        <div>
                            <label for="id_blogCategory" class="blogLabel" style="">Category</label>
                            <select class="form-select" style="margin-left: 14px;" name="blogCategory" id="id_blogCategory">
                                <option selected>Choose Category</option>
                                {% for category in Categories %}
                                    <option value="{{ category.id }}" class="blogCategoryOptions">{{ category.categoryTitle }}</option>
                                {% endfor %}
                            </select>
                        </div>
                    </div>
                    <div class="blog-submit" style="width: 100%;">
                        <label class="blogLabel" style="margin-top: 20px;" for="id_blogTitle">Title</label>
                        <input type="text" name="blogTitle" class="form-control placeholderBlog" id="id_blogTitle" placeholder="Title" style="width: 100%;" required>
                        <label class="blogLabel" for="id_blogContent" style="margin-top: 5px;">Content</label>
                        <textarea type="text" name="blogContent" class="form-control placeholderBlog" id="id_blogContent" placeholder="Start typing.." style="resize: none; height: 420px;" required></textarea>
                        <button id="room-name-submit" class="btn btn-primary blogsubmitbtn" type="submit" style="margin-top: 24px; font-size: 17px;">Upload</button>
                    </div>
                </div>
            </form>
        </div>
    </section>
    <br>
    <br>

    </div>
</div>

<div class="user_friend_chatroom">
    <div class="chat_room drop_shadow">
        <span>Chatrooms:</span>
        <div>
            <span>Create your own chat room:</span><br>
            <input id="room-name-input" style="width: 80%; margin-bottom: .1rem;" type="text" size="100"><br>
            <input id="room-name-submit" type="button" value="Enter">
        </div>
        <hr style="margin-top: 1rem;">
        <div class="server_chat_rooms_main">
            <div>Server Chat Rooms:</div>
            <div class="server_chat_rooms">
                <a href="{% url 'room' room_name='chat_room_1' %}">Chat Room 1 <i
                        class="fal fa-comments-alt"></i></a>
                <a href="{% url 'room' room_name='chat_room_2' %}">Chat Room 2 <i
                        class="fal fa-comments-alt"></i></a>
            </div>
            <div class="server_chat_rooms">
                <a href="{% url 'room' room_name='chat_room_3' %}">Chat Room 3 <i
                        class="fal fa-comments-alt"></i></a>
                <a href="{% url 'room' room_name='chat_room_4' %}">Chat Room 4 <i
                        class="fal fa-comments-alt"></i></a>
            </div>
        </div>
    </div>

    <div class="user_friends drop_shadow">
        <span>Friends:</span>
        {% for i in friend %}
        <div>
            <a href="{% url 'userprofile' i.id %}">
                <div><img src="{{ i.profile.pfp.url }}" class="new_user_pfp_feed" alt=""></div>
                <div>{{ i.first_name }} {{ i.last_name }}</div>
            </a>
        </div>
        {% endfor %}
    </div>
</div>

<div id="hide">
    <div class="textcopy">
        <div id="closebtn"><i class="fal fa-times-square"></i></div>
        <input id="textcopy" type="text" style="text-align: center; padding: 1rem;">
        <button onclick="copy()">Copy text</button>
        <div id="copied"></div>
    </div>
</div>

<script>
    function getURL() {
        var x = window.location.href;
        document.getElementById("textcopy").value = x;
        document.getElementById("hide").style.display = "block";
        document.getElementsByTagName("section").classList.add("opacity");
    }

    function copy() {
        var copyText = document.getElementById('textcopy');
        copyText.select();
        copyText.setSelectionRange(0, 99999)
        document.execCommand("copy");
        document.getElementById("copied").innerHTML = "Copied!";
    }

    document.getElementById("closebtn").addEventListener("click", function () {
        document.getElementById("hide").style.display = "none";
    });
</script>

<script>
$(".custom-select").each(function() {
  var classes = $(this).attr("class"),
      id      = $(this).attr("id"),
      name    = $(this).attr("name");
  var template =  '<div class="' + classes + '">';
      template += '<span class="custom-select-trigger">' + $(this).attr("placeholder") + '</span>';
      template += '<div class="custom-options">';
      $(this).find("option").each(function() {
        template += '<span class="custom-option ' + $(this).attr("class") + '" data-value="' + $(this).attr("value") + '">' + $(this).html() + '</span>';
      });
  template += '</div></div>';
  
  $(this).wrap('<div class="custom-select-wrapper"></div>');
  $(this).hide();
  $(this).after(template);
});
$(".custom-option:first-of-type").hover(function() {
  $(this).parents(".custom-options").addClass("option-hover");
}, function() {
  $(this).parents(".custom-options").removeClass("option-hover");
});
$(".custom-select-trigger").on("click", function() {
  $('html').one('click',function() {
    $(".custom-select").removeClass("opened");
  });
  $(this).parents(".custom-select").toggleClass("opened");
  event.stopPropagation();
});
$(".custom-option").on("click", function() {
  $(this).parents(".custom-select-wrapper").find("select").val($(this).data("value"));
  $(this).parents(".custom-options").find(".custom-option").removeClass("selection");
  $(this).addClass("selection");
  $(this).parents(".custom-select").removeClass("opened");
  $(this).parents(".custom-select").find(".custom-select-trigger").text($(this).text());
});
</script>
{% endblock %}

social_media_app/templates/social_media/home.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link type="text/css" rel="stylesheet" href="{% static 'social_media/css/home.css' %}">
    <title>Welcome</title>
</head>

<body>
    <header>
        <div class="wrapper">
            <div class="logo">
                <img src="https://1.bp.blogspot.com/-ata3-fQGA1M/UUxnSdNHqAI/AAAAAAAAAFI/Kb0gJs4YY_k/s1600/4.png" alt="">
            </div>
            <ul class="nav-area">
                <li><a href="{% url 'usersignin' %}">Signin</a></li>
                <li><a href="{% url 'usersignup' %}">SignUp</a></li>
            </ul>
        </div>
        <div class="welcome-text">
            <h1>Chatster</h1>
        </div>
    </header>

</body>
</html>

social_media_app/templates/social_media/setprofile.html
{% extends 'social_media/base.html' %}

{% block content %}

{% load static %}
<div class="settings_form">
    <form action="/savenewprofile/" method="POST" autocomplete="off" enctype="multipart/form-data">
        {% csrf_token %}
        {% if user.profile.cover.url %}
            <img src="{{ user.profile.cover.url }}" alt="" class="form_cover">
            <input type="file" name="cover" id="id_cover" class="inputfile">
        {% else %}
            <img src="{% static 'default/cover.jpg' %}" alt="" class="form_cover">
            <input type="file" name="cover" id="id_cover" class="inputfile">
        {% endif %}
        <label for="id_cover" class="change_cover">Change Cover</label>
        {% if user.profile.pfp.url %}
            <div class="pfp_show">
                <img src="{{ user.profile.pfp.url }}" alt="" class="form_pfp">
                <input type="file" name="pfp" id="id_pfp" class="inputfile">
                <label for="id_pfp" class="change_pfp">Change Pfp</label>
            </div>
        {% else %}
            <div class="pfp_show">
                <img src="{% static 'default/profile.jpg' %}" alt="" class="form_pfp">
                <input type="file" name="pfp" id="id_pfp" class="inputfile">
                <label for="id_pfp" class="change_pfp">Change Pfp</label>
            </div>
        {% endif %}
        <div class="user_form_info">
            <div class="name">
                <input type="text" required name="first_name" class="input_edit" placeholder="First Name" maxlength="30" id="id_first_name">
                <input type="text" required name="last_name" class="input_edit" placeholder="Last Name" maxlength="150" id="id_last_name">
            </div>
            <input type="text" name="username" class="input_edit" value="{{ user.username }}" maxlength="150" required="" id="id_username">
            <input type="email" name="email" class="input_edit" value="{{ user.email }}" maxlength="254" id="id_email">
            <textarea name="desc" cols="40" required rows="6" class="input_edit" id="id_desc" placeholder="Enter your profile Desc"></textarea>
            <div class="work_form">
                <span>Work:</span>
                <input type="text" name="occupation" required class="input_edit" maxlength="250" id="id_occupation" placeholder="Enter your work!">
            </div>
        </div>
        <button type="submit">Submit</button>
    </form>
</div>
{% endblock %}